### ISSUE TITLE
Main content and onboarding repo

### ISSUE THREAD

**Issue by trallard** [trallard/Shef_CodeFirst_Python#1]
Need to create main content on the course materials

- **Instructors**: how to add/structure content
- **Students:** how to use the course material, extra resources

Also need to create the super useful quick git sheet

**Comment by darrenvong** [comment]
This may be useful: https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf

**Comment by pawlean** [comment]
BTW BTW BTW Matt is a GitHub Campus Expert 🚩 so he'd be happy to come in and give some swag away and explain what GitHub and GitHub Education is when you talk about GitHub? @trallard

**Comment by darrenvong** [comment]
So it appears that the [LPTHW e-book](https://learnpythonthehardway.org/python3/) is no longer available for free completely - only the first 8 chapters can be read for free. We can either tell the girls to read that before the first session, or completely ditch it as a viable resource altogether.

The e-book also teaches Python 3 instead of 2.7, which in my opinion is better to do since 2.7 has hit its end-of-life for a few years now and really we should be teaching the latest stuff if possible. Also as Python 3 has been out for 9 years, library immaturity is not really a good argument anymore; most good libraries have ported across to Python 3.

Thoughts?

**Comment by trallard** [comment]
Well this is a bit weird since I seem to remember that they have to cover up to module 40 so if this is not out for free this might cause an inconvenience. 

@darrenvong  this is what I said ages ago!!! We need to teach Python 3 not 2.x 
If we go ahead with the installathon it should be easy to ensure they all have python 3 instead of 2 😄

**Comment by darrenvong** [comment]
If the LPTHW e-book isn't free anymore... does that mean we have to make up some exercises? Didn't you make some up already last semester @trallard? Also, I remember @ninas-sf has been telling me that she's learning Python off another e-book she's got. Maybe we can "borrow" some exercise materials from there?

**Comment by ninas-sf** [comment]
I bought Sam's python in 24 hours

You can get 2 chapters for free via pdf. I thought it was pretty good so I
bought it afterwards to work through. Happy to share the end of chapter
exercises. I can upload them.
