### ISSUE TITLE
Choose session to lead

### ISSUE THREAD

**Issue by trallard** [trallard/Shef_CodeFirst_Python#3]
We have 4 instructors now! so each should decide on 1-2 sessions to lead and prepare the material accordingly

Make sure the material is added here **before ** the sessions and assign a reviewer (another instructor not leading the session)

**Comment by ninas-sf** [comment]
I'd Like to lead session 7 when we set the project, I think I'll be more confident by then and its less language specific than some of the other sessions.

**Comment by darrenvong** [comment]
A quick note that we are in favour of restructuring the sessions slightly, with the following notable changes:
* Instead of covering (or re-visiting, assuming some have done the beginners course) git and the command line in Session 3 as a one-off, we will be encouraging the girls to use git every session by asking them to do **at least** a `git pull` to obtain the latest materials we have prepared for that session. As such, we can probably scrap Session 3 altogether, leaving us with more time to cover the Flask content.
* Ditching the Mailgun (email) API with a more interesting, fun API example instead. The Spotify API was mentioned as a potential replacement.

Reference to the course structure here: https://drive.google.com/file/d/0B8JSxb3eE6WUX0dmWE15RGU5Zm8/view

**Comment by darrenvong** [comment]
I'd be happy to co-lead Session 3/4 (Flask stuff) with @cgmcintyr as discussed in our meeting, since he's got some ideas on how to do it and I have some too based on experience from last semester on what needs clarifying.

**Comment by trallard** [comment]
Thanks for recording what we discussed on the meeting @darrenvong  you're great!

I would be happy to cover session 1 that would be then: Python basics, getting them to use Git (GitKraken) 

Also I am keen to lead the APIs session which might be (depending on how we go along) session 4.5 or 5

Still need to assign the following sessions:

- Session 2: user input, functions, loops (@ninas-sf ????)
- Session 6: deploying (@darrenvong or @cgmcintyr  ?????)

**Comment by ninas-sf** [comment]
I'm away for session 2 sorry, I would have done otherwise.

**Comment by trallard** [comment]
Also.... @paulienuh @lj1396  are you leading the ice-breaker????

**Comment by pawlean** [comment]
@trallard @lj1396 - That's right! Leave it to us :)

**Comment by darrenvong** [comment]
Happy to do **Session 6: deploying** again (even though @paulienuh will probs be annoyed by that idea 😉) as I've already got the materials from last time - it's perhaps just a case of re-writing it into the slides format!

**Comment by trallard** [comment]
@darrenvong yes just need to re-write this so that the objective of the class is something similar to 

> by the end of the session the teams will have successfully deployed to Heroku the barebones of their competition project

Also @cgmcintyr could you lead session 2??
